### ISSUE TITLE
Looking for GHL marketplace app SSO implementation documentation 

### ISSUE THREAD

**Issue by seankerr** [cbnsndwch/ghl-app-template#2]
I wouild like to apologize by creating an issue to get your attention. I'd be happy to send you a virtual coffee or beer for your help.

I am simply looking for any documentation that discusses how GHL is implementing SSO for marketplace apps. I see your flow diagram, but it's missing the key point of how the session is encrypted so that I can understand how to decrypt it. I thought decryption would be a bit more straight forward, similar to your NodeJS example, but it is not as easily implemented in Python. 

I'm using the pycryptodome library and the AES module that it provides. I'm base 64 decoding the SSO key and session payload into their byte equivalents. The data I'm seeing does line up with AES specifications for key size and block size on the payload. I've tried all the AES modes as well and I cannot get the decryption process to yield anything but gibberish. I'm assuming I should be seeing byte data that looks like ASCII json to be parsed as a last step, similar to your example.

Any help would be appreciated, as I'm stuck here. Let me know what I can do to show my appreciation.

**Comment by cbnsndwch** [comment]
Here's a bit more detailed walkthrough of the flow and how GHL implements SSO session encryption.

https://www.youtube.com/watch?v=3rveQDuVlR0

**Comment by cbnsndwch** [comment]
For anyone finding this issue later on, give this blog post by @seankerr a look:

https://seankerr.dev/posts/decrypting-highlevel-sso-session-using-python/

Closing this now but feel free to reopen it if needed.
